version: 0.2
       
phases:
  pre_build:
    # run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - echo Logging in to Docker Hub...
      - "docker login -u 'username' -p 'password'"
  build:
    # run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - "docker build -t engineerskillapiaws:latest . "
      - docker tag engineerskillapiaws:latest dockerusername/engineerskillapiaws:latest
    finally:
      - command
      - command
  post_build:
    # run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push dockerusername/engineerskillapiaws:latest
